openapi: 3.1.0
info:
  title: Clustron API
  version: 1.0.0
tags:
  - name: User
  - name: Auth
paths:
  /api/login/oauth/{provider}:
    get:
      operationId: Auth_loginGoogle
      parameters:
        - name: provider
          in: path
          required: true
          description: The OAuth2 provider to use for login.
          schema:
            $ref: '#/components/schemas/Auth.OAuthProviders'
        - name: c
          in: query
          required: true
          description: The callback URL of the OAuth2 login. [See details](https://clustron.atlassian.net/wiki/spaces/cd/pages/18219016/Backend+OAuth+JWT+Manual)
          schema:
            type: string
          explode: false
        - name: r
          in: query
          required: false
          description: The redirect URL for login callback.
          schema:
            type: string
          explode: false
      responses:
        '302':
          description: Redirection
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Auth
  /api/publickey:
    get:
      operationId: Settings_getPublicKey
      parameters:
        - name: short
          in: query
          required: false
          description: Get 10 head characters of publickey as short public key in 'publickey' field.
          schema:
            type: boolean
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Settings.PublicKey'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
    post:
      operationId: Settings_addPublicKey
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings.PublicKey'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings.AddPublicKeyRequest'
    delete:
      operationId: Settings_deletePublicKey
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings.DeletePublicKeyRequest'
  /api/refreshToken/{refreshToken}:
    get:
      operationId: Auth_refreshToken
      parameters:
        - name: refreshToken
          in: path
          required: true
          description: The refresh token to use for refreshing the access token.
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth.RefreshToken'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - Auth
  /api/settings:
    get:
      operationId: Settings_getUserSettings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings.UserSettings'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
    put:
      operationId: Settings_updateSettings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings.UserSettings'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings.UserSettings'
components:
  schemas:
    Auth.OAuthProviders:
      type: string
      enum:
        - google
        - nycu
    Auth.RefreshToken:
      type: object
      required:
        - accessToken
        - expirationTime
        - refreshToken
      properties:
        accessToken:
          type: string
          description: The new JWT
        expirationTime:
          type: integer
          description: The expiration date of the refresh token.
        refreshToken:
          type: string
          description: The new refresh token.
    Settings.AddPublicKeyRequest:
      type: object
      required:
        - title
        - publicKey
      properties:
        title:
          type: string
          description: The public key title set by the user.
        publicKey:
          type: string
          description: The public key of the user.
    Settings.DeletePublicKeyRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: The public key id in UUID format.
    Settings.PublicKey:
      type: object
      required:
        - id
        - title
        - publicKey
      properties:
        id:
          type: string
          description: The public key id in UUID format.
        title:
          type: string
          description: The public key title set by the user.
        publicKey:
          type: string
          description: The public key of the user.
    Settings.UserSettings:
      type: object
      required:
        - username
        - linuxUsername
      properties:
        username:
          type: string
          description: The real name of the user.
        linuxUsername:
          type: string
          description: The computer account name of the user.
    Versions:
      type: string
      enum:
        - 1.0.0
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
