openapi: 3.1.0
info:
  title: Clustron API
  version: 1.0.0
tags:
  - name: User
paths:
  /settings:
    get:
      operationId: Settings_getUserSettings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
  /settings/publickey:
    post:
      operationId: Settings_addPublicKey
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
    delete:
      operationId: Settings_deletePublicKey
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
  /settings/username:
    put:
      operationId: Settings_updateUsername
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
components:
  schemas:
    UserSettings:
      type: object
      required:
        - username
        - publicKey
      properties:
        username:
          type: string
        publicKey:
          type: array
          items:
            type: string
      description: User settings that are needed for access to the machine.
    Versions:
      type: string
      enum:
        - 1.0.0
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
