openapi: 3.1.0
info:
  title: Clustron API
  version: 1.0.0
tags:
  - name: User
paths:
  /api/publickey:
    get:
      operationId: Settings_getPublicKey
      parameters:
        - name: short
          in: query
          required: false
          description: Get 10 head characters of publickey as short public key in 'publickey' field.
          schema:
            type: boolean
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicKey'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
    post:
      operationId: Settings_addPublicKey
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicKey'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings.AddPublicKeyRequest'
    delete:
      operationId: Settings_deletePublicKey
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings.DeletePublicKeyRequest'
  /api/settings:
    get:
      operationId: Settings_getUserSettings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
    put:
      operationId: Settings_updateSettings
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '404':
          description: The server cannot find the requested resource.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettings'
components:
  schemas:
    PublicKey:
      type: object
      required:
        - id
        - title
        - publicKey
      properties:
        id:
          type: string
          description: The public key id in UUID format.
        title:
          type: string
          description: The public key title set by the user.
        publicKey:
          type: string
          description: The public key of the user.
    Settings.AddPublicKeyRequest:
      type: object
      required:
        - title
        - publicKey
      properties:
        title:
          type: string
          description: The public key title set by the user.
        publicKey:
          type: string
          description: The public key of the user.
    Settings.DeletePublicKeyRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: The public key id in UUID format.
    UserSettings:
      type: object
      required:
        - username
        - linuxUsername
      properties:
        username:
          type: string
          description: The real name of the user.
        linuxUsername:
          type: string
          description: The computer hostname of the user.
    Versions:
      type: string
      enum:
        - 1.0.0
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
